export const SUPPORTED_LANGUAGES = [
    { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '简体中文' },
    { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文' },
    { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
    { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'fil', name: 'Filipino / Tagalog', nativeName: 'Filipino' },
    { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
    { code: 'th', name: 'Thai', nativeName: 'ไทย' },
    { code: 'fa', name: 'Farsi', nativeName: 'فارسی' },
    { code: 'prs', name: 'Dari', nativeName: 'دری' },
    { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
    { code: 'my', name: 'Burmese', nativeName: 'မြန်မာဘာသာ' },
    { code: 'ko', name: 'Korean', nativeName: '한국어' },
    { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
    { code: 'am', name: 'Amharic', nativeName: 'አማርኛ' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
    { code: 'si', name: 'Sinhalese', nativeName: 'සිංහල' },
    { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
    { code: 'uk', name: 'Ukrainian', nativeName: 'Українська' },
    { code: 'ru', name: 'Russian', nativeName: 'Русский' },
    { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ' },
    { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
    { code: 'ja', name: 'Japanese', nativeName: '日本語' },
    { code: 'fr', name: 'French', nativeName: 'Français' },
    { code: 'es', name: 'Spanish', nativeName: 'Español' },
    { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
    { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
    { code: 'it', name: 'Italian', nativeName: 'Italiano' }
  ];